(function(){
  "use strict";
  if(window.__RAKIB_LICENSE_LOADER_RUNNING__) return;
  window.__RAKIB_LICENSE_LOADER_RUNNING__=true;
  const OWNER="raiyanrakib2006-code",REPO="rakib-license",BRANCH="main";
  const current=document.currentScript;
  const cdn=current&&current.src?current.src.split("?")[0].replace(/update\.js$/i,""):`https://cdn.jsdelivr.net/gh/${OWNER}/${REPO}@${BRANCH}/`;
  const licenseUrl=`https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/licenses.json`;
  const done=()=>{window.__RAKIB_LICENSE_LOADER_RUNNING__=false};
  function loadScript(url){return new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=url;s.async=true;s.onload=()=>{s.remove();resolve()};s.onerror=()=>{s.remove();reject(new Error("Required script could not be loaded."))};(document.head||document.documentElement).appendChild(s)})}
  async function sha256(text){if(!crypto||!crypto.subtle)throw new Error("Secure license verification is unavailable.");const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
  const old=document.getElementById("__rakib_license_overlay__");if(old)old.remove();
  const overlay=document.createElement("div");overlay.id="__rakib_license_overlay__";
  overlay.innerHTML=`<div class="r-card"><button class="r-close" type="button">×</button><div class="r-badge">LICENSE REQUIRED</div><h2>Rakib License Login</h2><p>Enter the complete RAKIB- license key.</p><input class="r-input" type="text" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="RAKIB-..."><button class="r-submit" type="button">Verify License</button><div class="r-msg"></div></div>`;
  const style=document.createElement("style");style.textContent=`#__rakib_license_overlay__{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.78);font-family:Arial,sans-serif}#__rakib_license_overlay__ *{box-sizing:border-box}#__rakib_license_overlay__ .r-card{position:relative;width:min(100%,390px);padding:28px;border:1px solid #2d3439;border-radius:18px;background:#11161a;color:#f5f7f8;box-shadow:0 24px 80px rgba(0,0,0,.55)}#__rakib_license_overlay__ h2{margin:8px 0;font-size:26px}#__rakib_license_overlay__ p{margin:0 0 18px;color:#aab4bb}#__rakib_license_overlay__ .r-badge{color:#00C853;font-size:11px;font-weight:800;letter-spacing:.12em}#__rakib_license_overlay__ .r-input,#__rakib_license_overlay__ .r-submit{width:100%;border-radius:10px;font:inherit}#__rakib_license_overlay__ .r-input{border:1px solid #374047;padding:13px 14px;background:#0b0f12;color:#fff;outline:none}#__rakib_license_overlay__ .r-input:focus{border-color:#00C853;box-shadow:0 0 0 3px rgba(0,200,83,.15)}#__rakib_license_overlay__ .r-submit{margin-top:12px;border:0;padding:13px 14px;background:#00C853;color:#06140b;font-weight:800;cursor:pointer}#__rakib_license_overlay__ .r-submit:disabled{opacity:.6;cursor:wait}#__rakib_license_overlay__ .r-msg{min-height:20px;margin-top:12px;font-size:13px;color:#ff9696}#__rakib_license_overlay__ .r-close{position:absolute;top:10px;right:12px;border:0;background:transparent;color:#9aa6ad;font-size:28px;cursor:pointer}`;overlay.appendChild(style);document.documentElement.appendChild(overlay);
  const input=overlay.querySelector(".r-input"),submit=overlay.querySelector(".r-submit"),msg=overlay.querySelector(".r-msg"),close=overlay.querySelector(".r-close");
  close.onclick=()=>{overlay.remove();done()};overlay.onclick=e=>{if(e.target===overlay){overlay.remove();done()}};
  async function verify(){const key=input.value.trim().toUpperCase();if(!key){msg.textContent="Enter the complete license key.";return}if(!key.startsWith("RAKIB-")){msg.textContent="The key must begin with RAKIB-.";return}submit.disabled=true;msg.style.color="#aab4bb";msg.textContent="Checking license...";try{const r=await fetch(licenseUrl+"?t="+Date.now(),{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error("The online license list could not be loaded.");const data=await r.json(),hash=await sha256(key),now=Date.now();const item=(data.licenses||[]).find(x=>x&&String(x.sha256||"").toLowerCase()===hash);if(!item)throw new Error("Invalid license.");if(item.active!==true)throw new Error("Inactive license.");if(item.expires&&Date.parse(item.expires)<now)throw new Error("Expired license.");msg.style.color="#58e58d";msg.textContent="License verified.";await loadScript(cdn+"main.js?t="+Date.now());setTimeout(()=>{overlay.remove();done()},300)}catch(e){msg.style.color="#ff9696";msg.textContent=e&&e.message?e.message:"License verification failed.";submit.disabled=false}}
  submit.onclick=verify;input.onkeydown=e=>{if(e.key==="Enter")verify()};setTimeout(()=>input.focus(),50);
})();